spring:
  application:
    name: demoapp

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dynamic-stud-96.clerk.accounts.dev

  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/realestate
    username: testuser
    password: "TestPass123!"

server:
  error:
    include-stacktrace: never
    include-message: never
    include-binding-errors: never
  tomcat:
    max-threads: 50
    max-spare-threads: 10

app:
  cors:
    allowed-origin: http://localhost:3000

stripe:
  key:
    secret: sk_test_51RdXw0Q05XjO94ClZ1PWcawabm8TdjiYPODemVl8jBq0jdvummCQNpcCyZCblkEct9XbqDCwbuzARy0uARnC2LvE00SL1AHEOz
  webhook:
    secret: whsec_0e948d9652dce5cba0c9ca6cf253cb639be8a97b6b79f2e8b535c833abf265f9

flyway:
  locations: classpath:db/migration
  baseline-on-migrate: true
  validate-on-migrate: true

STPAPIClient:
  shared:
    publishableKey: "pk_test_51RdXw0Q05XjO94Cl1tWYTanEgKtv2Zla7QSQvh4yvarYzNOxlZdSCvLcNMEmfhY9alfO20iHMYlN1QmZbFdptqgA00EIa3bHyw"
